### ISSUE TITLE
Bad Request on https://raw.githubusercontent.com/iloveeclipse/plugins/latest/

### ISSUE THREAD

**Issue by rubenporras** [iloveeclipse/plugins#3]
Hi iloveeclipse,

accessing the documented update site https://raw.githubusercontent.com/iloveeclipse/plugins/latest/ returns a 400: Invalid request, are you aware of the problem?

Regards

**Comment by iloveeclipse** [comment]
Yes, there is no problem. Directory browsing is not allowed.
Try https://raw.githubusercontent.com/iloveeclipse/plugins/latest/site.xml instead.
