### ISSUE TITLE
Unable to download jars from Eclipse update site

### ISSUE THREAD

**Issue by pSub** [iloveeclipse/plugins#4]
While trying to fix broken urls in the nixpkgs repository (NixOS/nixpkgs#111896) I stumbled upon your blog post about your migration to Github.

Unfortunately the link to the https://raw.githubusercontent.com/iloveeclipse/plugins/latest/ returns HTTP 400 and everything I tried to download the files I need de.loskutov.BytecodeOutline._<version>.jar and de.loskutov.BytecodeOutline.feature_<version>.jar resulted in 400 and 404 return codes. I tried it with version `2.5.0.201711011753-5a57fdf`.

 Is there a way to download those files or is there something broken at the moment?

**Comment by iloveeclipse** [comment]
The site is fully functional. The directory does not allow listing contents, that is usual on github. Only if you knlw the exact file url. These are in site.xml.

**Comment by pSub** [comment]
https://raw.githubusercontent.com/iloveeclipse/plugins/latest/site.xml works. Thank you!

**Comment by prusnak** [comment]
However, the site.xml nor https://github.com/iloveeclipse/plugins/tree/latest contain `de.loskutov.BytecodeOutline....jar` and `de.loskutov.BytecodeOutline.feature.jar` - where does one find them?

**Comment by prusnak** [comment]
Ah, I now see the BytecodeOutline is in a separate repo: https://github.com/iloveeclipse/bytecodeoutline thanks
